PUT http://localhost:8080/api/user/profile/password
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTc2NDU4Nzc0MCwiZXhwIjoxNzY0Njc0MTQwfQ.wI9K4oypC3EBKMDLZZA01c48Fd3HAMeUBSkoS-eqHnY

{
    "oldPassword" : "123456",
    "newPassword" : "114514"
}